idf_component_register(
    SRCS
        "main.c"
        "measure.c"
        "normalize.c"
        "ble_config.c"
        "gsm.c"
    INCLUDE_DIRS
        "."
    REQUIRES
        bt              
        driver          
        esp_event       
        esp_netif       
        nvs_flash             
        nmea0183_parser_main  
        esp_driver_ledc
    PRIV_REQUIRES
        esp_driver_spi
        esp_driver_gpio
        esp_wifi
        esp_modem
        mqtt          
        esp_http_client                  
        lis331
        lsm6
)