(part "H3LIS331DLTR"
    (packageRef "LIS3DHTR")
    (interface
        (port "1" (symbPinId 1) (portName "VDD_IO") (portType POWER))
        (port "2" (symbPinId 2) (portName "NC_1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "NC_2") (portType INOUT))
        (port "4" (symbPinId 4) (portName "SCL_SPC") (portType INOUT))
        (port "5" (symbPinId 5) (portName "GND_1") (portType GROUND))
        (port "6" (symbPinId 6) (portName "SDA_SDI_SDO") (portType INOUT))
        (port "7" (symbPinId 7) (portName "SDO_SA0") (portType INOUT))
        (port "8" (symbPinId 8) (portName "CS") (portType INPUT))
        (port "9" (symbPinId 9) (portName "INT2") (portType INPUT))
        (port "10" (symbPinId 10) (portName "RESERVED_1") (portType INOUT))
        (port "11" (symbPinId 11) (portName "INT1") (portType INPUT))
        (port "12" (symbPinId 12) (portName "GND_2") (portType GROUND))
        (port "13" (symbPinId 13) (portName "GND_3") (portType GROUND))
        (port "14" (symbPinId 14) (portName "VDD") (portType POWER))
        (port "15" (symbPinId 15) (portName "RESERVED_2") (portType INOUT))
        (port "16" (symbPinId 16) (portName "GND_4") (portType GROUND))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "511-H3LIS331DLTR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/STMicroelectronics/H3LIS331DLTR?qs=TAo1I7FhABsAZFqkqNUSRA%3D%3D")
    (property "Manufacturer_Name" "STMicroelectronics")
    (property "Manufacturer_Part_Number" "H3LIS331DLTR")
    (property "Description" "Accelerometers Low Pwr Hi G 3-axis Digital Acceleromtr")
    (property "Datasheet_Link" "https://www.st.com/resource/en/datasheet/h3lis331dl.pdf")
    (property "symbolName1" "H3LIS331DLTR")
)
