(part "SLW-1276864-4A-D"
    (packageRef "SLW12768644AD")
    (interface
        (port "1" (symbPinId 1) (portName "NC") (portType INOUT))
        (port "2" (symbPinId 2) (portName "COM") (portType INOUT))
        (port "3" (symbPinId 3) (portName "NO") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "162")
    (property "Mouser_Part_Number" "179-SLW-1276864-4A-D")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Same-Sky/SLW-1276864-4A-D?qs=1Kr7Jg1SGW90vOt02EYiag%3D%3D")
    (property "Manufacturer_Name" "Same Sky")
    (property "Manufacturer_Part_Number" "SLW-1276864-4A-D")
    (property "Description" "SLW-1276864-4A-D - 12.7 x 6.8 x 6.4 mm, 2 mm Raised Slide Actuator, Vertical, Through Hole, Slide Switch")
    (property "Datasheet_Link" "https://www.sameskydevices.com/product/resource/SLW-1276864-4A-D.pdf")
    (property "symbolName1" "SLW-1276864-4A-D")
)
