(part "ADM7155ACPZ-04-R7"
    (packageRef "SON50P300X300X80-9N-D")
    (interface
        (port "1" (symbPinId 1) (portName "VREG") (portType INOUT))
        (port "2" (symbPinId 2) (portName "VOUT") (portType INOUT))
        (port "3" (symbPinId 3) (portName "BYP") (portType INOUT))
        (port "4" (symbPinId 4) (portName "GND") (portType INOUT))
        (port "5" (symbPinId 5) (portName "REF_SENSE") (portType INOUT))
        (port "6" (symbPinId 6) (portName "REF") (portType INOUT))
        (port "7" (symbPinId 7) (portName "EN") (portType INOUT))
        (port "8" (symbPinId 8) (portName "VIN") (portType INOUT))
        (port "9" (symbPinId 9) (portName "PAD") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "584-ADM7155ACPZ-04R7")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Analog-Devices/ADM7155ACPZ-04-R7?qs=iCT64eccu7j%2Fv45ioAdAhA%3D%3D")
    (property "Manufacturer_Name" "Analog Devices")
    (property "Manufacturer_Part_Number" "ADM7155ACPZ-04-R7")
    (property "Description" "LDO Voltage Regulators 600mA Ultra-Low-Nois High-PSRR LDO ADJ")
    (property "Datasheet_Link" "https://componentsearchengine.com/Datasheets/1/ADM7155ACPZ-04-R7.pdf")
    (property "symbolName1" "ADM7155ACPZ-04-R7")
)
