(part "CL31A226MOCLNNC"
    (packageRef "CAPC3216X100N")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "32")
    (property "Mouser_Part_Number" "187-CL31A226MOCLNNC")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Samsung-Electro-Mechanics/CL31A226MOCLNNC?qs=X6jEic%2FHinD7wddQJyY%252BZw%3D%3D")
    (property "Manufacturer_Name" "SAMSUNG")
    (property "Manufacturer_Part_Number" "CL31A226MOCLNNC")
    (property "Description" "Ceramic capacitor 1206 X5R 16V 22uF Samsung Electro-Mechanics 1206 CL 22uF Ceramic Multilayer Capacitor, 16 V, +85C, X5R Dielectric, +/-20% SMD")
    (property "Datasheet_Link" "https://datasheet.datasheetarchive.com/originals/distributors/Datasheets_SAMA/f725fe7da06092c10c109ee50d712988.pdf")
    (property "symbolName1" "CL31A226MOCLNNC")
)
