(part "NEO-F10N-00B"
    (packageRef "NEOF10N00B")
    (interface
        (port "1" (symbPinId 1) (portName "SAFEBOOT_N") (portType INOUT))
        (port "2" (symbPinId 2) (portName "RESERVED_1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "TIMEPULSE") (portType INOUT))
        (port "4" (symbPinId 4) (portName "EXTINT") (portType INOUT))
        (port "5" (symbPinId 5) (portName "RESERVED_2") (portType INOUT))
        (port "6" (symbPinId 6) (portName "RESERVED_3") (portType INOUT))
        (port "7" (symbPinId 7) (portName "RESERVED_4") (portType INOUT))
        (port "8" (symbPinId 8) (portName "RESET_N") (portType INOUT))
        (port "9" (symbPinId 9) (portName "VCC_RF") (portType INOUT))
        (port "10" (symbPinId 10) (portName "GND_1") (portType INOUT))
        (port "11" (symbPinId 11) (portName "RF_IN") (portType INOUT))
        (port "12" (symbPinId 12) (portName "GND_2") (portType INOUT))
        (port "13" (symbPinId 13) (portName "GND_3") (portType INOUT))
        (port "14" (symbPinId 14) (portName "LNA_EN") (portType INOUT))
        (port "15" (symbPinId 15) (portName "RESERVED_5") (portType INOUT))
        (port "16" (symbPinId 16) (portName "RESERVED_6") (portType INOUT))
        (port "17" (symbPinId 17) (portName "RESERVED_7") (portType INOUT))
        (port "18" (symbPinId 18) (portName "RESERVED_8") (portType INOUT))
        (port "19" (symbPinId 19) (portName "RESERVED_9") (portType INOUT))
        (port "20" (symbPinId 20) (portName "TXD") (portType INOUT))
        (port "21" (symbPinId 21) (portName "RXD") (portType INOUT))
        (port "22" (symbPinId 22) (portName "V_BCKP") (portType INOUT))
        (port "23" (symbPinId 23) (portName "VCC") (portType INOUT))
        (port "24" (symbPinId 24) (portName "GND_4") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "377-NEO-F10N-00B")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/u-blox/NEO-F10N-00B?qs=Imq1NPwxi76uVH%2FItRhLgw%3D%3D")
    (property "Manufacturer_Name" "u-blox")
    (property "Manufacturer_Part_Number" "NEO-F10N-00B")
    (property "Description" "GNSS / GPS Modules u-blox F10 GNSS module Flash, TCXO, SAW, LNA LCC, 12x16 mm, 250 pcs/reel")
    (property "Datasheet_Link" "https://content.u-blox.com/sites/default/files/documents/NEO-F10N_DataSheet_UBX-23002117.pdf")
    (property "symbolName1" "NEO-F10N-00B")
)
