(part "CL10B104KO8NNNC"
    (packageRef "CAPC1608X90N")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "32")
    (property "Mouser_Part_Number" "187-CL10B104KO8NNNC")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Samsung-Electro-Mechanics/CL10B104KO8NNNC?qs=349EhDEZ59pqoJFRnk4a8w%3D%3D")
    (property "Manufacturer_Name" "SAMSUNG")
    (property "Manufacturer_Part_Number" "CL10B104KO8NNNC")
    (property "Description" "Samsung Electro-Mechanics 0603 (1608M) 100nF Multilayer Ceramic Capacitor MLCC 16V dc +/-10% SMD CL10B104KO8NNNC")
    (property "Datasheet_Link" "https://datasheet.datasheetarchive.com/originals/distributors/Datasheets_SAMA/482ee8b8a1396945e1abac0da9778f7f.pdf")
    (property "symbolName1" "CL10B104KO8NNNC")
)
