(part "SS14"
    (packageRef "DIOM5227X270N")
    (interface
        (port "1" (symbPinId 1) (portName "K") (portType INOUT))
        (port "2" (symbPinId 2) (portName "A") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "512-SS14")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/onsemi-Fairchild/SS14?qs=mVVXn4M53U%252BvrBaFv5vr4w%3D%3D")
    (property "Manufacturer_Name" "onsemi")
    (property "Manufacturer_Part_Number" "SS14")
    (property "Description" "High-Current Capability, Low VF; Glass-Passivated Junctions")
    (property "Datasheet_Link" "https://www.onsemi.com/pub/Collateral/SS19-D.PDF")
    (property "symbolName1" "SS14")
)
