idf_component_register(
    SRCS
        "main.c"
        "measure.c"
        "normalize.c"
        "communicate.c"
        "gsm.c"
    INCLUDE_DIRS
        "."
    REQUIRES
        driver          
        esp_event       
        esp_netif       
        nmea0183_parser_main  
    PRIV_REQUIRES
        esp_driver_spi
        esp_driver_gpio
        esp_wifi
        esp_modem
        nvs_flash
        lis331
        lsm6
)